### ISSUE TITLE
What button

### ISSUE THREAD

**Issue by Crazygird** [xlak/alphabetic#11]
Just wondering? what do I click?

**Comment by Crazygird** [comment]
I only see this:
404 Not Found
nginx
Click here to try again 🕶️

**Comment by idkidk738374** [comment]
its patched rn use something like nebula proxy

**Comment by bro-my-username-got-blocked** [comment]
woah mide what r u doing here

**Comment by Crazygird** [comment]
😳 bro that was year ago
