### ISSUE TITLE
SSL Handshake Failed

### ISSUE THREAD

**Issue by Brandon200815** [xlak/alphabetic#3]
Is anyone else getting this error?

**Comment by xlak** [comment]
That error usually indicates that the proxy server crashed. It's also possible that the Replit servers went down for a moment (which is where the proxy is running).

I'm looking into the issue. Next time it happens please post a screenshot if possible.

**Comment by xlak** [comment]
The proxy server is now set to auto-restart if it crashes. It's also monitored by UptimeRobot so I know right away if there are issues.

Closed due to inactivity.
