### ISSUE TITLE
Click here button not redirecting anymore

### ISSUE THREAD

**Issue by CBA-DiamondKing** [xlak/alphabetic#7]
Chromebook managed - Lenovo 500e 2nd gen

I follow all the steps, including the bookmarklet and the ctrl-p print, then when I click the button, it no longer redirect me. I know what it's supposed to do because it was working yesterday.

**Comment by xlak** [comment]
Somehow both the main and backup proxy servers automatically deactivated today. Not sure how that happened since they are periodically pinged to make them stay up.

Everything is up again now.
